setTimeout(function(){ document.getElementsByClassName("src-components-___sizes-dropdown__iconArrow___2BXHg")[0].click(); }, 2000);
setTimeout(function(){ document.querySelector("#app > div > div.src-components-___container__container___Grvi1.src-components-___container__show___28O40 > div.src-components-___pdp__available___2OJ67 > div.src-components-___product__container___2Cq_M > div.src-components-___product__productInfo___aOq2I > div.src-components-___add-to-bag-form__container___VykWT > div.src-components-___sizes-dropdown__container___1xcFK > div.src-components-___sizes-dropdown__sizes___ztM1k > div > ul > li:nth-child(1)").click() }, 2000);
setTimeout(function(){ document.querySelector("#app > div > div.src-components-___container__container___Grvi1.src-components-___container__show___28O40 > div.src-components-___pdp__available___2OJ67 > div.src-components-___product__container___2Cq_M > div.src-components-___product__productInfo___aOq2I > div.src-components-___add-to-bag-form__container___VykWT > button > span").click() }, 2000);
setTimeout(function(){ document.querySelector("#app > div > div:nth-child(1) > div > div > div > div.checkout_page___bUohj.fullHeader___2_gX_ > div > div > main > div.col-s-12.no-gutters.cart-page__actions___30zQO.gl-hidden-s-m.gl-vspace-bpall-medium > div:nth-child(1) > button > span").click() }, 2000);

document.getElementsByClassName("src-components-___sizes-dropdown__iconArrow___2BXHg")[0].click();

document.querySelector("#app > div > div.src-components-___container__container___Grvi1.src-components-___container__show___28O40 > div.src-components-___pdp__available___2OJ67 > div.src-components-___product__container___2Cq_M > div.src-components-___product__productInfo___aOq2I > div.src-components-___add-to-bag-form__container___VykWT > div.src-components-___sizes-dropdown__container___1xcFK > div.src-components-___sizes-dropdown__sizes___ztM1k > div > ul > li:nth-child(1)").click()
sleep(1000)
document.querySelector("#app > div > div.src-components-___container__container___Grvi1.src-components-___container__show___28O40 > div.src-components-___pdp__available___2OJ67 > div.src-components-___product__container___2Cq_M > div.src-components-___product__productInfo___aOq2I > div.src-components-___add-to-bag-form__container___VykWT > button > span").click()
document.querySelector("#app > div > div:nth-child(1) > div > div > div > div.checkout_page___bUohj.fullHeader___2_gX_ > div > div > main > div.col-s-12.no-gutters.cart-page__actions___30zQO.gl-hidden-s-m.gl-vspace-bpall-medium > div:nth-child(1) > button > span").click()